version: "3.8"

volumes: 
  logs:

services:
  #
  # Container to make fake logs
  #
  logs:
    build:
      context: docker/logs
      dockerfile: "Dockerfile"
    volumes:
      - logs:/logs/
    restart: "always"

  #
  # Tool container for importing/exporting dashboards.
  #
  tools:
    build:
      context: docker/tools
      dockerfile: "Dockerfile"
    volumes:
      - .:/mnt
      - logs:/logs/
    restart: "always"

  #
  # Container to continuously ping hosts.
  #
  ping:
    build:
      context: docker/ping
      dockerfile: "Dockerfile"
    environment:
      #
      # Host to ping.  Can be hostname or IP.  Space-delimited.
      # Note that DNS lookups may fail, so consider pinging some IPs...
      #
      HOSTS: "google.com amazon.com google-dns cloudflare-dns "
      #
      # Comment the previous line and uncomment this one if you'd like to ping 
      # some hosts on different continents.
      #
      #HOSTS: "google.com amazon.com google-dns cloudflare-dns cheetah.jp leopard.se"
    volumes:
      - logs:/logs/
      - ./hosts.txt:/etc/hosts
    restart: "always"

  #
  # Get metrics from ping logs for Prometheus.
  #
  ping-metrics:
    build:
      context: docker/ping-metrics
      dockerfile: "Dockerfile"
    volumes:
      - .:/mnt
      - logs:/logs/
    restart: "always"


  #
  # Container to read metrics from SEPTA Regional Rail.
  #
  septa:
    build:
      context: docker/septa
      dockerfile: "Dockerfile"
    volumes:
      - .:/mnt
      - logs:/logs/
    restart: "always"


  #
  # Read logs from files and ingest into Loki.
  #
  promtail:
    image: grafana/promtail
    volumes:
      - logs:/logs/
      - ./config:/mnt/config
      - ./data/promtail:/mnt/var
      - /var/log:/var/log
    command: -config.file=/mnt/config/promtail-config-docker.yaml
    ports:
      - "9081:9080"
    restart: "always"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686 

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./config/otel.yaml:/etc/otel-config.yaml
    command:
      '--config=/etc/otel-config.yaml'
    environment:
      LOGSPOUT: ignore
    depends_on:
      - jaeger

  #
  # Telegraf reads system metrics, and will expose them to Prometheus and send them to Loki
  #
  telegraf:
    image: telegraf:latest
    volumes:
      - type: bind
        source: ./config/telegraf.conf
        target: /etc/telegraf/telegraf.conf
    ports:
      - "8094:8094"
    restart: "always"

  #
  # The Loki database for storing logs.
  #
  loki:
    image: grafana/loki:latest
    user: root
    volumes:
      - ./config:/mnt/config
      - ./data/loki-data:/tmp/loki
      - ./data/loki-wal:/tmp/wal
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    restart: "always"

  #
  # Prometheus
  #
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    # networks:
    #   - default
    #   - outer
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: "always"


  #
  # Grafana, for viewing via the UI.
  #
  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: "always"
    depends_on:
      - jaeger
      - otel
      - telegraf



# networks:
#   outer:
#     name: "outer"
#     external: true
