version: "3"

volumes:
  logs:

services:

  #
  # Tool container for importing/exporting dashboards.
  #
  tools:
    build:
      context: docker/tools
      dockerfile: "Dockerfile"
    volumes:
      - .:/mnt
      - logs:/logs/
    restart: "always"

  #
  # Read logs from files and ingest into Loki.
  #
  promtail:
    image: grafana/promtail
    volumes:
      - logs:/logs/
      - ./config:/mnt/config
      - ./data/promtail:/mnt/var
      - /var/log:/var/log
    command: -config.file=/mnt/config/promtail-config-docker.yaml
    ports:
      - "9081:9080"
    restart: "always"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./config/otel.yaml:/etc/otel-config.yaml
    command:
      '--config=/etc/otel-config.yaml'
    environment:
      LOGSPOUT: ignore
    depends_on:
      - jaeger

  #
  # The Loki database for storing logs.
  #
  loki:
    image: grafana/loki:latest
    volumes:
      - ./config:/mnt/config
      - ./data/loki-data:/tmp/loki
      - ./data/loki-wal:/tmp/wal
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    restart: "always"

  #
  # Prometheus
  #
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    expose:
      - "9090"
    # networks:
    #   - default
    #   - outer
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: "always"


  #
  # Grafana, for viewing via the UI.
  #
  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: "always"
    depends_on:
      - jaeger
      - otel
