version: "3.8"

volumes:
  logs:

services:
  #
  # Container to make fake logs
  #
  logs:
    build:
      context: docker/logs
      dockerfile: "Dockerfile"
    volumes:
      - logs:/logs/
    restart: "always"

  #
  # Tool container for importing/exporting dashboards.
  #
  tools:
    build:
      context: docker/tools
      dockerfile: "Dockerfile"
    volumes:
      - .:/mnt
      - logs:/logs/
    restart: "always"

  telegraf:
    image: telegraf:latest
    volumes:
      - type: bind
        source: ./config/telegraf.conf
        target: /etc/telegraf/telegraf.conf
    environment:
      # - INFLUX_TOKEN=J_omfjEIKXcPiz-0O0F-jRs_4XHsC1FqMZEZs7G9TUgUT0R7oqL6fSBX28OqTBdRxYq4SSjpieT_velKujIliA==
      # - INFLUX_TOKEN=dFfGoCoCqN39-KOpzLi8XbDtcxRJsfl4zlrK4xJPny9_N5oNaD0oNBOuPhKYdAwFBqiVRCiGGXO3lyw5w_HV_Q==
      - INFLUX_TOKEN=gYJBP2hdiqQSXXb669m9qri-y9y6RlY8EUzI9SJi2X-rZnCmKeud909aO_P8J0qIM0IcZr6U4_dvIc_ZBuRxhA==
    ports:
      - "8094:8094"
      - "8125:8125"
    restart: "always"
    depends_on:
      - influxdb
    links:
      - influxdb

  influxdb:
    image: influxdb:latest
    restart: always
    environment:
      - INFLUXDB_DB=influx
      # - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./data/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    restart: "always"
    depends_on:
      - telegraf
      - influxdb

  aifs-collector:
    build:
      context: ./aifs-collector
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - ./aifs-collector/app:/app # Mounts the host 'app' directory to '/app' in the container
